package com.gaekdam.gaekdambe.iam_service.permission_type.command.domain.seeds;

public enum PermissionTypeKey {
  // 리포트 (REPORT)
  REPORT_READ,
  REPORT_DETAIL_READ,
  REPORT_DASHBOARD_CREATE,
  REPORT_DASHBOARD_UPDATE,

  // 회원 (MEMBER)
  MEMBER_LIST_READ,

  // 직원 (EMPLOYEE) - 요청하신 대로 변경 완료
  EMPLOYEE_CREATE,              // 직원 생성
  EMPLOYEE_UPDATE,              // 직원 수정
  EMPLOYEE_DELETE,              // 직원 삭제
  EMPLOYEE_DETAIL_READ,         // 직원 상세조회
  EMPLOYEE_LIST_READ,           // 직원 리스트 조회

  // 고객 (CUSTOMER)
  CUSTOMER_READ,
  CUSTOMER_LIST_READ,
  CUSTOMER_UPDATE,
  CUSTOMER_DELETE,

  // 고객 메모 (CUSTOMER_MEMO)
  CUSTOMER_MEMO_READ,
  CUSTOMER_MEMO_LIST_READ,
  CUSTOMER_MEMO_UPDATE,
  CUSTOMER_MEMO_DELETE,

  // 멤버십 기준 (MEMBERSHIP_POLICY)
  MEMBERSHIP_POLICY_READ,
  MEMBERSHIP_POLICY_CREATE,
  MEMBERSHIP_POLICY_UPDATE,
  MEMBERSHIP_POLICY_DELETE,

  // 멤버십 (MEMBERSHIP)
  MEMBERSHIP_READ,
  MEMBERSHIP_UPDATE,

  // 로열티 기준 (LOYALTY_POLICY)
  LOYALTY_POLICY_READ,
  LOYALTY_POLICY_CREATE,
  LOYALTY_POLICY_UPDATE,
  LOYALTY_POLICY_DELETE,

  // 로열티 (LOYALTY)
  LOYALTY_READ,
  LOYALTY_UPDATE,

  // 고객 활동 및 타임라인
  CUSTOMER_ACTIVITY_READ,
  CUSTOMER_TIMELINE_READ,
  CHECK_IN_OUT_LIST_READ,
  CHECK_IN_CREATE,
  CHECK_OUT_CREATE,
  FACILITY_USAGE_LIST_READ,

  // 문의 (INQUIRY)
  INQUIRY_LIST_READ,
  INQUIRY_DETAIL_READ,

  // 사건사고 (ACCIDENT)
  ACCIDENT_LIST_READ,
  ACCIDENT_DETAIL_READ,
  ACCIDENT_CREATE,
  ACCIDENT_DELETE,

  // 메시지 (MESSAGE)
  MESSAGE_READ,
  MESSAGE_CREATE,
  MESSAGE_UPDATE,
  MESSAGE_DELETE
}
