package com.gaekdam.gaekdambe.iam_service.permission_type.command.domain.seeds;

public enum PermissionTypeKey {
    // 리포트 (REPORT)
    REPORT_LIST,
    REPORT_READ,
    REPORT_DASHBOARD_CREATE,
    REPORT_DASHBOARD_UPDATE,

    // 회원 (MEMBER)
    MEMBER_LIST,

    // 형식 : (리소스)_(기능)
    EMPLOYEE_LIST,                //직원 리스트 조회
    EMPLOYEE_READ,                //직원 상세 조회
    EMPLOYEE_CREATE,              // 직원 생성
    EMPLOYEE_UPDATE,              // 직원 수정
    EMPLOYEE_DELETE,              // 직원 삭제

    // 고객 (CUSTOMER)
    CUSTOMER_READ,
    CUSTOMER_LIST,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,

    // 고객 메모 (CUSTOMER_MEMO
    // )
    CUSTOMER_MEMO_CREATE,
    CUSTOMER_MEMO_LIST,
    CUSTOMER_MEMO_READ,
    CUSTOMER_MEMO_UPDATE,
    CUSTOMER_MEMO_DELETE,

    // 멤버십 기준 (MEMBERSHIP_POLICY)
    MEMBERSHIP_POLICY_LIST,
    MEMBERSHIP_POLICY_READ,
    MEMBERSHIP_POLICY_CREATE,
    MEMBERSHIP_POLICY_UPDATE,
    MEMBERSHIP_POLICY_DELETE,


    // 로열티 기준 (LOYALTY_POLICY)
    LOYALTY_POLICY_LIST,
    LOYALTY_POLICY_READ,
    LOYALTY_POLICY_CREATE,
    LOYALTY_POLICY_UPDATE,
    LOYALTY_POLICY_DELETE,


    // 고객 활동 및 타임라인
    CUSTOMER_TIMELINE_READ,
    RESERVATION_LIST,
    RESERVATION_READ,
    RESERVATION_PACKAGE_LIST,
    CHECK_IN_OUT_LIST,
    STAYS_LIST,

    FACILITY_USAGE_LIST,

    // 문의 (INQUIRY)
    INQUIRY_LIST,
    INQUIRY_READ,

    // 사건사고 (ACCIDENT)
    ACCIDENT_CREATE,
    ACCIDENT_LIST,
    ACCIDENT_READ,
    ACCIDENT_DELETE,

    // 메시지 (MESSAGE)

    MESSAGE_CREATE,
    MESSAGE_LIST,
    MESSAGE_READ,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,

    // 권한
    PERMISSION_CREATE,
    PERMISSION_LIST,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,
}
