name: Create Release

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: develop-release-${{ github.run_number }}
          name: develop-release-${{ github.run_number }}
          prerelease: true
          generate_release_notes: true
